spring:
  application:
    name: ArtEcommerce

  # Neon DB config
  datasource:
    url: ${NEON_DB_URL}
    driver-class-name: org.postgresql.Driver

  # JPA configs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Java Mail Sender API config.
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com

server:
  port: 8080

frontend:
  origin: ${FRONTEND_ORIGIN}

jwt:
  secret:
    key: ${JWT_SECRET}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}