spring:
  application:
    name: ArtEcommerce

  # Neon DB config
  datasource:
    url: ${NEON_DB_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080